filebeat.prospectors:

- input_type: log

  paths:
    - /var/log/squid/access.log
    
  document_type: squid

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.100.103:5044"]
  bulk_max_size: 1024
  ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]
