filebeat.prospectors:

- input_type: log

  paths:
    #- /var/log/*.log
    - /var/log/auth.log
    - /var/log/syslog
    
  document_type: syslog

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.100.103:5044"]
  bulk_max_size: 1024
  ssl.certificate_authorities: ["/etc/pki/tls/certs/logstash-forwarder.crt"]

